# Generated by Django 5.0 on 2024-10-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigaaa', '0002_rename_valor1_nota_nota1_rename_valor2_nota_nota2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ano',
            field=models.DateField(),
        ),
    ]
