# Generated by Django 5.0 on 2024-10-31 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigaaa', '0004_aluno_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota2',
        ),
    ]
